# Generated by Django 3.0.5 on 2020-04-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='average_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='refuel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='refuel',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='distance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ride',
            name='entry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
